### ISSUE TITLE
Where did the autobrew formula go?

### ISSUE THREAD

**Issue by yihui** [autobrew/homebrew-cran#29]
Since this project supercedes https://github.com/r-hub/homebrew-cran, I wonder where `autobrew` is now: https://github.com/r-hub/homebrew-cran/blob/master/Formula/autobrew.rb Thanks!

**Comment by jeroen** [comment]
I have switched to another design, because homebrew itself was too volatile to create a stable build system.

We now create [bundles](https://github.com/autobrew/archive), which are archives that contain static libs + all dependencies for a given system library. So those can be downloaded on-the-fly by a package, or installed on a build server.

What exactly would you like to do?

**Comment by yihui** [comment]
I see.

> What exactly would you like to do?

I wanted this feature: https://github.com/r-hub/homebrew-cran#how-we-force-static-linking

**Comment by jeroen** [comment]
For any particular package?

**Comment by yihui** [comment]
No particular package, but some binary packages that are not built on CRAN. I just wanted to try static linking since it sounds like a clever idea, although I don't really understand your magic. Anyway, this is not particularly important. Thanks!
