### ISSUE TITLE
Can anyone use this infrastructure?

### ISSUE THREAD

**Issue by rdinnager** [autobrew/homebrew-cran#37]
Hi @jeroen, I just had a question about this autobrew infrastructure. I have an R package that has a dependency on a library that is not on CRAN (SuiteSparse), but it is available via brew. I am trying to setup a system to compile static libraries and have my package download them at installation time, which seems to be what this setup does for mac (I already have such a system working for Windows). My question is, can I add new packages to autobrew by pull request for use by my package? If so, is there a document that describes the necessary steps? From looking around here, I think I would need to add a Formula for this repo (if I need to make modifications to the standard Formula), make an autobrew/bundler script to make bottles and upload them to autobrew/archive, and then make a autobrew/scripts script for downloading the correct bottle during installation of the R package? Do I have that right, more or less? Apologies, I am not that familiar with MacOS but would like to be able to submit my package to CRAN eventually. Would appreciate any advice you might have. Thanks!

**Comment by jeroen** [comment]
It is not an official system and not documented but you are free to use it.

Having a quick look, the `suite-sparse` homebrew package already contains static libraries, however it's dependency `metis` does not. So we either need to rebuild it without the metis dependency, or provide a metis static build (depending on if you think this dependency is important).

You should also submit the formula to https://github.com/autobrew/homebrew-core because CRAN still targets older versions of macos.

**Comment by rdinnager** [comment]
Thanks very much for the fast and helpful reply. Much appreciated. The `metis` dependency is not needed, and the Windows version doesn't use it, so for consistency we should probably rebuild `suite-sparse` without `metis`. I will have a go at setting something up, and make a PR if it looks good.

**Comment by rdinnager** [comment]
Since my question is answered I will close this now. Thanks!
